[package]
name = "teddybear-crypto"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
categories.workspace = true

[dependencies]
ssi-dids = { workspace = true }
ssi-jwk = { workspace = true }
teddybear-did-key = { path = "../teddybear-did-key" }
multibase = { workspace = true }
thiserror = { workspace = true }
