[package]
name = "teddybear-vc"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
categories.workspace = true

[dependencies]
ssi-json-ld = { workspace = true }
ssi-ldp = { workspace = true }
ssi-vc = { workspace = true }

chrono = "0.4.31"
jsonschema = { version = "0.17.1", default-features = false }
serde = { workspace = true }
serde_json = "1.0.113"
serde_json_path = { version = "0.6.4", default-features = false }
teddybear-crypto = { workspace = true }
thiserror = { workspace = true }
