[package]
name = "teddybear-vc"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
categories.workspace = true

[features]
query = ["grdf", "iref", "rdf-types", "static-iref"]

[dependencies]
ssi-json-ld = { workspace = true }
ssi-ldp = { workspace = true }
ssi-vc = { workspace = true }

chrono = "0.4.31"
grdf = { version = "0.16.3", optional = true }
iref = { version = "2.2.3", optional = true }
jsonschema = { version = "0.17.1", default-features = false }
rdf-types = { version = "0.12.19", optional = true }
serde = { workspace = true }
serde_json = "1.0.113"
serde_json_path = { version = "0.6.4", default-features = false }
static-iref = { version = "2.0.0", optional = true }
teddybear-crypto = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
