[package]
name = "teddybear-vc"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
categories.workspace = true

[features]
query = ["grdf", "iref", "itertools", "rdf-types", "static-iref"]

[dependencies]
ssi-json-ld = { workspace = true }
ssi-ldp = { workspace = true }
ssi-vc = { workspace = true }

chrono = "0.4.31"
grdf = { version = "0.16.3", optional = true }
iref = { version = "2.2.3", optional = true }
itertools = { workspace = true, optional = true }
rdf-types = { version = "0.12.19", optional = true }
static-iref = { version = "2.0.0", optional = true }
teddybear-crypto = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
tokio = { workspace = true }
