[package]
name = "teddybear-vc"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
categories.workspace = true

[dependencies]
ssi-claims = { workspace = true }
ssi-dids-core = { workspace = true }
ssi-json-ld = { workspace = true }
ssi-vc = { workspace = true }
ssi-verification-methods = { workspace = true }

itertools = "0.13.0"
serde = { workspace = true }
teddybear-crypto = { workspace = true }
thiserror = { workspace = true }
