name: "Bump version"
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: New version name (without the "v" prefix)

jobs:
  bump-version:
    name: Bump Teddybear version
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Activate Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Bump version
        run: nix develop .#ci --command cargo set-version ${{ inputs.version }}
      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          title: "chore: bump version to ${{ inputs.version }}"
          commit-message: "chore: bump version to ${{ inputs.version }}"
          branch: "bump-${{ inputs.version }}"
          reviewers: ivan770
