name: "Bump version"
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: New version name (without the "v" prefix)

jobs:
  bump-version:
    name: Bump Teddybear version
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Activate Nix cache
        uses: nix-community/cache-nix-action@v5
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', 'flake.lock', '**/Cargo.lock', '**/yarn.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size: 2684354560 # 2.5 GB
      - name: Bump version
        run: nix develop .#ci --command cargo set-version ${{ inputs.version }}
      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          title: "chore: bump version to ${{ inputs.version }}"
          commit-message: "chore: bump version to ${{ inputs.version }}"
          branch: "bump-${{ inputs.version }}"
          reviewers: ivan770
