name: "Check"
on:
  pull_request:
    branches:
      - main
jobs:
  check:
    name: Check Nix flake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Run flake checks
        run: nix flake check
