name: "Check"

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    if: ${{ !startsWith(github.event.pull_request.head.ref, 'bump-') }}
    name: Check Nix flake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Activate Nix cache
        uses: nix-community/cache-nix-action@v5
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', 'flake.lock', '**/Cargo.lock', '**/yarn.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size: 2684354560 # 2.5 GB
      - name: Run flake checks
        run: nix flake check
