name: "Check"

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    if: ${{ !startsWith(github.event.pull_request.head.ref, 'bump-') }}
    name: Check Nix flake
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Activate Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run flake checks
        run: nix flake check
